GET http://localhost:3000

### register a use POST /AUTH/LOGIN
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "kha",
    "email": "khadeptrai@gmail.com",
    "password": "123456789"
}

### login a use POST /AUTH/LOGIN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "khadeptrai@gmail.com",
    "password": "123456789"
}
