### Register user (if not already registered)
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "kha",
    "email": "khadeptrai@gmail.com",
    "password": "123456789"
}

### Login user and get JWT token
# @name login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "khadeptrai@gmail.com",
    "password": "123456789"
}

### Create a new transaction (expense)
# @name create
POST http://localhost:3000/api/transactions
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "amount": 100000,
    "date": "2024-06-01T12:00:00Z",
    "category_id": 1,
    "note": "Ăn trưa", 
    "type": "outcome"
}

### Get all transactions for user
GET http://localhost:3000/api/transactions
Authorization: Bearer {{login.response.body.token}}

### Get a specific transaction by ID
GET http://localhost:3000/api/transactions/2
Authorization: Bearer {{login.response.body.token}}

### Get all transactions for user with month filter
GET http://localhost:3000/api/transactions?month=2024-06
Authorization: Bearer {{login.response.body.token}}

### Update the transaction
PUT http://localhost:3000/api/transactions/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "amount": 120000,
    "date": "2024-06-01T12:00:00Z",
    "category_id": 1,
    "note": "Ăn trưa cập nhật",
    "type": "outcome"
}

### Delete the transaction
DELETE http://localhost:3000/api/transactions/5
Authorization: Bearer {{login.response.body.token}}

### Search transactions by note
GET http://localhost:3000/api/transactions/search?searchTerm=Ăn trưa
Authorization: Bearer {{login.response.body.token}}

### Create budget
POST http://localhost:3000/api/budgets
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "amount": 100000,
    "month": "2024-06"
}

### Delete budget
DELETE http://localhost:3000/api/budgets/1
Authorization: Bearer {{login.response.body.token}}

### Create saving
POST http://localhost:3000/api/savings
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "goal_name": "Mua xe",
    "target_amount": 50000000
}

### Get all savings
GET http://localhost:3000/api/savings
Authorization: Bearer {{login.response.body.token}}

### Update saving
PUT http://localhost:3000/api/savings/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

### Delete saving
DELETE http://localhost:3000/api/savings/1
Authorization: Bearer {{login.response.body.token}}

### Create loan
POST http://localhost:3000/api/loans_debts
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "amount": 1000000,
    "person": "John Doe",
    "due_date": "2024-12-31",
    "type": "loan"
}

### Get all loans

